### PR TITLE
Fixed preserve option inside at-rules

### LINKED ISSUE #42: Option 'preserve' doesn't work inside @media rules
input css with option preserve = true
```css
@media screen and (max-width: 700px) {
    :root {
        --color-link: purple;
    }
}
.link {
    color: var(--color-link);
}
```

output
```css
@media screen and (max-width: 700px) {
    .link {
        color: purple;
    }
}
```

Expected output
```css
@media screen and (max-width: 700px) {
    .link {
        color: purple;
        color: var(--color-link);
    }
}
```

### PR DESCRIPTION
**Pull request by muftiev**
Fix #42

### CODE REVIEW

**Comment by MadLittleMods** [comment]
Thanks for the PR @muftiev :grinning: 

Please add some tests that previously fail and now work

**Comment by muftiev** [comment]
Updated tests with new cases  😄

**Comment by MadLittleMods** [comment]
@muftiev Let's split those off into their own `preserve-variables-in-media` file

**Comment by muftiev** [comment]
Ok, done)

**Comment by muftiev** [comment]
@MadLittleMods Will you accept it? 😄

**Comment by MadLittleMods** [comment]
@muftiev Most likely, will try to get this in by Monday. Feel free to ping

**Comment by muftiev** [comment]
@MadLittleMods Ping to remind you to deal with this PR

**Comment by muftiev** [comment]
@MadLittleMods Really wish to use your module in my project, but I need this fix 😄

**Comment by MadLittleMods** [comment]
Sorry for the wait, I brushed across this tab everyday.

@muftiev Thanks again for the contribution, I'll get this onto a release pronto.

**Comment by muftiev** [comment]
Thank you!

**Comment by MadLittleMods** [comment]
@muftiev [v0.5.2](https://github.com/MadLittleMods/postcss-css-variables/blob/master/CHANGELOG.md#v052---2016-8-24) now pushed to npm, https://www.npmjs.com/package/postcss-css-variables

**Comment by muftiev** [comment]
Great! 😄

**Pull request merged**
